### ISSUE TITLE
Enable REST API

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wcs11#50]

**Comment by keshav-nangare** [comment]
@dstenger 

Currently the test implementation in a single file and it's hard to implement the REST interface with the current implementation.

**Comment by keshav-nangare** [comment]
Fixed with this commit: 9ae096adc46bcd80679fbe6244997a4ca4449d81 & PR: #54

**Comment by lgoltz** [comment]
I've added a missing jar to the lib folder of the docker container and updated the docker.teamengine.version. The ETS can be executed via REST with http://localhost:8081/teamengine/rest/suites/wcs11/run?url=http://ows.eox.at/cite/mapserver?service=wcs%26version=1.1.1%26request=getcapabilities but throws an exception:
```
d1ea0a> Testing suite wcs:suite-auto in Test Mode with defaultResult of Pass ...
d1ea0a> ******************************************************************************************************************************
d1ea0a>    Testing wcs:Main-auto type Mandatory in Test Mode with defaultResult Pass (abde4f9c-6137-411a-80b4-fbcb270c6fc9)...
d1ea0a>       Assertion: The Implementation Under Test (IUT) satisfies all applicable
d1ea0a>                   assertions. There are 177 tests in total. Depending on the capabilities
d1ea0a>                        of the server, some tests are skipped. These are recorded in the
d1ea0a>                       detailed results for each type of request.
d1ea0a>       WCS 1.1.1 URL is http://ows.eox.at/cite/mapserver?service=wcs&version=1.1.0&request=getcapabilities.
d1ea0a> ******************************************************************************************************************************
d1ea0a>       Testing wcs:GetCapabilities-main type Mandatory in Test Mode with defaultResult Pass (abde4f9c-6137-411a-80b4-fbcb270c6fc9/d1e24015_1)...
d1ea0a>          Assertion: All assertions for "GetCapabilities" conformance are satisfied.
d1ea0a>          The service metadata document version number is 1.1.1.
d1ea0a>          The EqualUpdateSequence value is 20121123T120000Z.
d1ea0a>          The URL for KVP encoding is http://ows.eox.at/cite/mapserver?.
d1ea0a>          The URL for XML encoding is http://ows.eox.at/cite/mapserver?.
d1ea0a>          XML encoding is not supported.
d1ea0a>          sections-supported: true.
d1ea0a> Exception in thread "AWT-EventQueue-0" java.awt.HeadlessException:
d1ea0a> No X11 DISPLAY variable was set, but this program performed an operation which requires it.
d1ea0a> 	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
d1ea0a> 	at java.awt.Window.<init>(Window.java:536)
d1ea0a> 	at java.awt.Frame.<init>(Frame.java:420)
d1ea0a> 	at java.awt.Frame.<init>(Frame.java:385)
d1ea0a> 	at javax.swing.JFrame.<init>(JFrame.java:189)
d1ea0a> 	at com.occamlab.te.SwingForm.<init>(SwingForm.java:205)
d1ea0a> 	at com.occamlab.te.SwingForm.<init>(SwingForm.java:36)
d1ea0a> 	at com.occamlab.te.SwingForm$Invoker.run(SwingForm.java:56)
d1ea0a> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
d1ea0a> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
d1ea0a> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
d1ea0a> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
d1ea0a> 	at java.awt.EventQueue$3.run(EventQueue.java:703)
d1ea0a> 	at java.security.AccessController.doPrivileged(Native Method)
d1ea0a> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
d1ea0a> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
d1ea0a> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
d1ea0a> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
d1ea0a> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
d1ea0a> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
d1ea0a> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
d1ea0a> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
Some parameters requires user input: https://github.com/opengeospatial/ets-wcs11/blob/bbcdb6844f01296925a2feaa14371d3e509ee2fd/src/main/scripts/ctl/GetCapabilities.xml#L117-L152 
Instead this parameters should be passed with the REST URL, e.g: http://localhost:8081/teamengine/rest/suites/wcs11/run?url=http://ows.eox.at/cite/mapserver?service=wcs%26version=1.1.1%26request=getcapabilities&MinimalValue=0&MaximalValue=15&BogusValue=bogus

@keshav-nangare Can you take a look at this?

**Comment by keshav-nangare** [comment]
@lgoltz 

Fixed this issue and disabled the HTML form to appear in REST API execution and passed the required parameter via query-parameter.
